#!/bin/sh
#
# @name Surface Constructor USV
#
# @type Underwater Robot
# @class Underwater Robot
#
# @output Motor1 Thruster 0 - Front Right
# @output Motor2 Thruster 1 - Front Left
# @output Motor3 Thruster 2 - Rear Right
# @output Motor4 Thruster 3 - Rear Left
#
# @maintainer Your Name <your.email@example.com>
#

. ${R}etc/init.d/rc.usv_defaults

# Airframe configuration
param set-default CA_AIRFRAME 7
param set-default CA_ROTOR_COUNT 4
param set-default MAV_TYPE 14

# All thrusters bidirectional
param set-default CA_R_REV 15

# Thruster geometry - Square configuration (0.4m side, 45° inward)
# Thruster 0: Front-Right
param set-default CA_ROTOR0_PX 0.20
param set-default CA_ROTOR0_PY 0.20
param set-default CA_ROTOR0_PZ 0.00
param set-default CA_ROTOR0_AX 0.707
param set-default CA_ROTOR0_AY -0.707
param set-default CA_ROTOR0_AZ 0.00
param set-default CA_ROTOR0_CT 6.5
param set-default CA_ROTOR0_KM 0.05

# Thruster 1: Front-Left
param set-default CA_ROTOR1_PX 0.20
param set-default CA_ROTOR1_PY -0.20
param set-default CA_ROTOR1_PZ 0.00
param set-default CA_ROTOR1_AX 0.707
param set-default CA_ROTOR1_AY 0.707
param set-default CA_ROTOR1_AZ 0.00
param set-default CA_ROTOR1_CT 6.5
param set-default CA_ROTOR1_KM 0.05

# Thruster 2: Rear-Right
param set-default CA_ROTOR2_PX -0.20
param set-default CA_ROTOR2_PY 0.20
param set-default CA_ROTOR2_PZ 0.00
param set-default CA_ROTOR2_AX 0.707
param set-default CA_ROTOR2_AY 0.707
param set-default CA_ROTOR2_AZ 0.00
param set-default CA_ROTOR2_CT 6.5
param set-default CA_ROTOR2_KM 0.05

# Thruster 3: Rear-Left
param set-default CA_ROTOR3_PX -0.20
param set-default CA_ROTOR3_PY -0.20
param set-default CA_ROTOR3_PZ 0.00
param set-default CA_ROTOR3_AX 0.707
param set-default CA_ROTOR3_AY -0.707
param set-default CA_ROTOR3_AZ 0.00
param set-default CA_ROTOR3_CT 6.5
param set-default CA_ROTOR3_KM 0.05

# PWM output configuration
param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104

param set-default PWM_MAIN_MIN1 1100
param set-default PWM_MAIN_MIN2 1100
param set-default PWM_MAIN_MIN3 1100
param set-default PWM_MAIN_MIN4 1100

param set-default PWM_MAIN_MAX1 1900
param set-default PWM_MAIN_MAX2 1900
param set-default PWM_MAIN_MAX3 1900
param set-default PWM_MAIN_MAX4 1900

param set-default PWM_MAIN_DIS1 1500
param set-default PWM_MAIN_DIS2 1500
param set-default PWM_MAIN_DIS3 1500
param set-default PWM_MAIN_DIS4 1500
